id: P05635848
initial_creation_type: input
source_metadata:
  title: Lama Rigdzin Nyima Series
  language: en
  description: Texts by Lama Rigdzin Nyima (rig 'dzin nyi ma, b. 1931), a tertön from
    Golok.
  volume:
    32cd9261deaf466c8469cbaaa7d1d148:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T00:33:40.753075'
last_modified_at: '2022-03-01T00:33:40.753083'
